### ISSUE TITLE
Issues for Installation

### ISSUE THREAD

**Issue by DHGK** [pcahan1/singleCellNet#16]
Hi SingleCellNet Team,

When I try to install the package, I got the following error and not sure what to deal with:
Error in i.p(...) : 
  (converted from warning) installation of package ‘C:/Users/\~1/AppData/Local/Temp/Rtmp0S7yMI/file1128ee055cf/singleCellNet_0.1.0.tar.gz’ had non-zero exit status

Would you guys have any idea what may this happened and how to fix this? Really appreciate all your help.

Best

**Comment by yuqiyuqitan** [comment]
Hi,
Could you send me your code and the full error message? i am unable to replicate your error. And did you install via install_github("pcahan1/singleCellNet") ?

**Comment by DHGK** [comment]
Thanks, I realized it was some r issue that caused the error. I removed the package and installed successfully.
