### ISSUE TITLE
'mc.cores' > 1 is not supported on Windows

### ISSUE THREAD

**Issue by DHGK** [pcahan1/singleCellNet#17]
Hi SingleCellNet Team,

When I try to find best pairs and transform query data, and train classifier using my windows computer. It gives me the following error:

Error in mclapply(myPatternG, sc_testPattern, expDat = tmpPdat, mc.cores = mcCores) : 'mc.cores' > 1 is not supported on Windows

Is there anyway to bypass the case of mc.cores>1 ?

Thanks

**Comment by yuqiyuqitan** [comment]
Hi,
I have updated the training code to bypass the parallel computing for Windows computer, however, that will drastically increase the computing time. Below is the new code for your reference.

`#' @export
ptGetTop <-function(expDat, 
  cell_labels, 
  topX=50, 
  sliceSize = 5e3,
  ncores = detectCores()){

  ans<-vector()
  genes<-rownames(expDat)

  mcCores <- 1
  if(ncores>1){
    mcCores <- ncores - 1
  }
  cat(ncores, "  --> ", mcCores,"\n")

  # make a data frame of pairs of genes that will be sliced later
  if(FALSE){
    cat("Making pairTable\n")
    ngenes<-nrow(expDat)
    genes<-rownames(expDat)
    genes1<-vector()
    genes2<-vector()
    for(i in 1:ngenes){ # replace with combn?
      for(j in 1:ngenes){
        if(j>i){
          genes1<-append(genes1, genes[i])
          genes2<-append(genes2, genes[j])        
        }
      }
    }

    pairTab = data.frame(genes1=genes1, genes2=genes2)
    pairNames<-paste(pairTab[,1], "_",pairTab[,2], sep='')
    pairTab <- cbind(pairTab, pairName=pairNames)
  }

  pairTab<-makePairTab(genes)
  
  # setup tmp ans list of sc_testPattern
  cat("setup ans and make pattern\n")
  grps<-unique(cell_labels)
  myPatternG<-sc_sampR_to_pattern(as.character(cell_labels))
  statList<-list()
  for(grp in grps){
    statList[[grp]]<-data.frame()
  }
  
  # make the pairedDat, and run sc_testPattern
  cat("make pairDat on slice and test\n")
  nPairs = nrow(pairTab)
  cat("nPairs = ",nPairs,"\n")
  str = 1
  stp = min(c(sliceSize, nPairs))
  while(str <= nPairs){
    if(stp>nPairs){
      stp <- nPairs
    }
  cat(str,"-", stp,"\n")
  tmpTab<-pairTab[str:stp,]
  tmpPdat<-ptSmall(expDat, tmpTab)

    
  ### new
  if (Sys.info()[['sysname']] == "Windows") {
    tmpAns<-lapply(myPatternG, sc_testPattern, expDat=tmpPdat)
  }
  else {
    tmpAns<-parallel::mclapply(myPatternG, sc_testPattern, expDat=tmpPdat, mc.cores=mcCores) # this code cannot run on windows
  }
 
  for(gi in seq(length(myPatternG))){
        grp<-grps[[gi]]
        #cat(i, " grp: ",grp,"\n")
        statList[[grp]]<-rbind( statList[[grp]],  tmpAns[[grp]])
      }


      str = stp+1
      stp = str + sliceSize - 1   
  }

  cat("compile results\n")
  for(grp in grps){
      tmpAns<-findBestPairs(statList[[grp]], topX)
      ans<-append(ans, tmpAns)
    }
    unique(ans)
}

makePairTab<-function(genes){
  pTab<-t(combn(genes, 2))
  colnames(pTab)<-c("genes1", "genes2")
  pTab<-cbind(pTab, pairName=paste(pTab[,1], "_",pTab[,2], sep=''))
  pTab
}

ptSmall<-function
(expDat,
 pTab){
  npairs = nrow(pTab)
  ans<-matrix(0, nrow=npairs, ncol=ncol(expDat))
  genes1<-as.vector(pTab[,"genes1"])
  genes2<-as.vector(pTab[,"genes2"])

    for(i in seq(nrow(pTab))){
      #cat(genes1[i], ": ", genes2[i],"\n")
      ans[i,]<-as.numeric(expDat[genes1[i],]>expDat[genes2[i],]) 
    }
  colnames(ans)<-colnames(expDat)
  rownames(ans)<-as.vector(pTab[,"pairName"])
  ans
}
`

**Comment by DHGK** [comment]
It works! Thank you!
