### ISSUE TITLE
query_transform function error

### ISSUE THREAD

**Issue by DHGK** [pcahan1/singleCellNet#18]
Hi singleCellNet community,

I was trying to train a mouse gastrulation atlas data. For the binary matrix generation step, I got this error: 

system.time(expQtransAll<-query_transform(expTMraw[cgenesA,rownames(stTest)], xpairs))
Error in intI(j, n = d[2], dn[[2]], give.dn = FALSE) :
  no 'dimnames[[.]]': cannot use character indexing
Timing stopped at: 73.59 11.98 85.57

I'm pretty show expTMraw keeps both rownames and colnames, but I don't really understand why it says "no 'dimnames[[.]]': cannot use character indexing".

Sincerely hope anyone could help me with this.

thanks!

**Comment by yuqiyuqitan** [comment]
Hi,
I couldn't replicate your error. Could you check what is the rownames of your stTest and if they correspond to the colnames of expTMraw in format?

**Comment by MichaelFarid** [comment]
Hi, what worked for me is transforming expTMraw into a data frame first before running that command using data.frame(expTMraw). After than you can run query_transform and then to be safe, expQtransAll[is.na(expQtransAll)]=0 before continuing with the remaining steps. Hope that works for you as well!

**Comment by DHGK** [comment]
> Hi, what worked for me is transforming expTMraw into a data frame first before running that command using data.frame(expTMraw). After than you can run query_transform and then to be safe, expQtransAll[is.na(expQtransAll)]=0 before continuing with the remaining steps. Hope that works for you as well!

Hi MichaelFarid, thanks a lot for the suggestion, it worked for me as well!

**Comment by yuqiyuqitan** [comment]
Thanks Michael!
