### ISSUE TITLE
Cell type with less than 100 cells

### ISSUE THREAD

**Issue by Pikachu233** [pcahan1/singleCellNet#19]
Hi everyone,

I'm trying to use SCN to build a cross-species classifier. The issue is that for my dataset, there are few rare cell types with cell number less than 100 (some of them are even less than 10). I'm aware that I could change ncells in splitcommon function. However, I'm not sure if I reduce ncells, will it cause any underfit effect for the trained classifier? Does anyone also encounter such issue? Would you mind sharing the way how you guys tackle it?

Thanks!

**Comment by yuqiyuqitan** [comment]
Hi, I have used ncell = 50 to train classifiers using Tabula Muris data and have obtained very satisfactory performance of the classifier. So I would start there. Additionally, it is important to assess your classifier performance with heldout data using assess_comm(), plot_PRs() and plot_metrics() particularly for those rare cell types with less than 10 cells. It is my experiences that classifier/or classifier category built with just less than 10 cells shows poorer performance.
