### ISSUE TITLE
"rand" category

### ISSUE THREAD

**Issue by DHGK** [pcahan1/singleCellNet#20]
Hi!

I know you guys have mentioned in your preprint that "we created 100
randomized cell expression profiles (nrand = 100) to train up a “rand” category in the SCN-TP
classifier, which can help in cases where some cell types that are present in the query data are
not included in the training data (Step 2b)". However, would you guys mind explaining more on what do you mean by "create randomized cell expression profiles"? Do you guys simulate the expression for 100 cells or you randomly choose 100 cells from the dataset to form the category, or else?

thanks!

**Comment by yuqiyuqitan** [comment]
Hey, so the randomized single cell profiles are created by randomly sampling/select gene expression from single cell profiles in the training data and combining that into a "new" or "random" cell. The idea behind this step is to create a positive control, and a "garbage collector" when the query cell type is not in the training.

**Comment by DHGK** [comment]
@yuqiyuqitan ,

Thanks so much for the quick reply. it's all clear now!

Best!

**Comment by concatenize** [comment]
A related question: for this procedure, does singleCellNet automatically seed the PRNG before randomizing expression profiles? For benchmarking, it will be useful to know whether results should be exactly repeatable or just close. Thanks!

**Comment by yuqiyuqitan** [comment]
Hi, SCN doesn't automatically seed the PRNG within, but you are welcome to set the seed before you begin the analysis!

**Comment by concatenize** [comment]
Good to know. Thank you!
