### ISSUE TITLE
Issues in going through the provided data

### ISSUE THREAD

**Issue by bencch** [pcahan1/singleCellNet#21]
When i went through the provided data with the code, i got stuck at accessing classifier. 
After entering the code " tm_heldoutassessment = assess_comm(ct_scores = classRes_val_all, stTrain = stTrain, stQuery = stTest, dLevelSID = "cell", classTrain = "newAnn", classQuery = "newAnn", nRand = 50)", the following error message popped up:

Error in AUC(tmp$recall, tmp$precision, method = AUCmethod) : 
  unused argument (method = AUCmethod)

**Comment by yuqiyuqitan** [comment]
Hi, it should just be a loading library(DescTools) problem. I also altered the code in Github to enforce that function to work. Let me know if you still have errors.

**Comment by yuqiyuqitan** [comment]
You can install from github again (without the ref tag) or library(DesTools). either option should work.
