### ISSUE TITLE
Some singleCellNet error

### ISSUE THREAD

**Issue by nanshanjin** [pcahan1/singleCellNet#23]
HI:
There are some error when i run the singleCellNet,
first,the plot_metrics() error:
plot_metrics(tm_heldoutassessment)
Error in p1 | p4 :
operations are possible only for numeric, logical or complex types
second,the umap() error:
system.time(umPrep_HS<-prep_umap_class(crParkall, stQuery, nrand=50, dLevel="description1", sid="sample_name", topPC=5))
PCA
UMAP
Error in umap(pcRes$x[, 1:topPC], min_dist = 0.5) :
could not find function "umap"
Timing stopped at: 0.408 0.023 0.434

Thank U
NS

**Comment by yuqiyuqitan** [comment]
Hi NS,

Do you have Patchwork and umap packages installed?
`devtools::install_github("thomasp85/patchwork")
install.packages("umap")`

**Comment by nanshanjin** [comment]
> Hi NS,
> 
> Do you have Patchwork and umap packages installed?
> `devtools::install_github("thomasp85/patchwork") install.packages("umap")`

OK，thank U very much
