### ISSUE TITLE
Error in combn: n < m

### ISSUE THREAD

**Issue by ekernf01** [pcahan1/singleCellNet#24]
Hi singleCellNet devs. I am trying out this tool and receiving the following error:

```
Error in combn(1, 2) : n < m
```

It seems to happen whenever one of the cluster labels is the empty string or NA. You may want to add an error message for this case. Here's an example.

```
singleCellNet::scn_train(
  stTrain = data.frame(cluster = c("", "A", "B"), id = 1:300),
  dLevel = "cluster", colName_samp = "id",
  expTrain = matrix(rnorm(26*300), ncol = 300) %>% 
    set_rownames(LETTERS) %>%
    set_colnames(1:300) 
)
```

**Comment by yuqiyuqitan** [comment]
Hi, Thanks for using and improving our code! I have incorporated it to catch both NAs and empty string into master branch. If you reinstall SCN again, you will see the error message.

`if(sum(grps == "")>1 | sum(is.na(grps))>1){
    stop("There is NA or empty string in your dLevel. Please remove them before proceeding.")
  }`

cheers!

**Comment by ekernf01** [comment]
Great! Thank you!
