### ISSUE TITLE
Error in classMat

### ISSUE THREAD

**Issue by juliaszusz** [pcahan1/singleCellNet#26]
Hi Yuqi,

Thanks so much for your help in troubleshooting yesterday. I have just about gone through the whole process with my own datasets, and I have run into this error when trying to generate a heatmap for classifying my query data to my training data:

**sc_hmClass(crQueryall, sgrp, max=5000, isBig=TRUE, cCol=F, font=8)**
Error in classMat[, cells2] : subscript out of bounds

The previous step ran fine:
**sgrp = as.vector(stQuery$description)
names(sgrp) = as.vector(stQuery$sample_name)
grpRand =rep("rand", nqRand)
names(grpRand) = paste("rand_", 1:nqRand, sep='')
sgrp = append(sgrp, grpRand)**

and the table with the query data looks like the same format as the vignette query data. 

Any help with figuring out this error would be greatly appreciated!

Julia

**Comment by yuqiyuqitan** [comment]
From what you provided here, i can't tell where the error is coming from.
 
1) please check to see if the sample_name of your stQuery is corresponding to the colnames of crQueryall. 
2)
names(grpRand) = paste("rand_", 1:nqRand, sep='') should probably be:
names(grpRand) = paste("rand_", 1:nqRand, sep="'')

**Comment by juliaszusz** [comment]
Hi Yuqi,

Thanks for responding. There was an issue with my metadata file and everything is better now and it works. For some reason the cell names were not entirely matching with a few typos, and also the csv file with the metadata needed to be loaded with "row.names = 1" to be able to match the cell IDs up with the cell IDs in the expression matrix.

Thanks for all of your help and for building a great tool!

Julia
