### ISSUE TITLE
Reducing memory requirements

### ISSUE THREAD

**Issue by concatenize** [pcahan1/singleCellNet#30]
Hi SCN devs! I am running SCN and I keep running out of RAM.  The training set has 32k genes, 5464 cells, and 60 cell types (so 30*59 = 1770 pairs). I'm using the parameters below. Is this problem something you would expect, and do you have any advice? I have already downsampled from a much larger number of cells, but maybe the issue is the high number of cell *types*?

Thank you!

```
nTopGenes = 10
nRand = 0
nTrees = 1000
nTopGenePairs = 25
```

**Comment by yuqiyuqitan** [comment]
Hi, I actually was able to train SCN on my Mac locally with datasets larger than 5k and with more number of pairs. However, if RAM is an issue locally, you could consider working with cloud computing services such as AWS. We are working on developing SCN in python, it is slightly faster, but I don't have a good sense of whether it is more RAM efficient.

**Comment by concatenize** [comment]
OK, thanks for the quick response! I may be able to lighten the load on my Mac by closing other programs, or else I can try cloud computing.
