### ISSUE TITLE
extractSCE object "exp_type" not found

### ISSUE THREAD

**Issue by FatRabbitTao** [pcahan1/singleCellNet#33]
Hi, in the extractSCE function, I saw
@param sce_object
@param exp_type
However, the actual param are sce_object and exp_slot_name, whereas the code calls exp_type
as a result, when I run extractSCE, I always get the error "object exp_type not found"

According to the @param it does seem to me that exp_type is a parameter and not a value defined elsewhere
May I know whether this is a bug and whether it can be fixed?

Thanks in advance

**Comment by yuqiyuqitan** [comment]
This error is telling you that your SCE object doesn't have the **counts slot**. The default parameter for exp_slot_name is "counts". You can adjust the exp_type to be "normcounts", or "logcounts" which will extract corresponding expression slots from SCE assuming you have them.
