### ISSUE TITLE
clean the TM10X(stList_tm10x_full, sampTab) data into a structure as same as the example data

### ISSUE THREAD

**Issue by lyuguol** [pcahan1/singleCellNet#34]
@yuqiyuqitan Dear Yuqi, many thanks for developing this awesome tool!! 

Could you show me how to prepare the stTM (metadata) for the TM10X('stList_tm10x_full.rda'),i.e. making its structure as same as the example data(sampTab_TM_053018)?

Thank you and best,

Guoliang

**Comment by yuqiyuqitan** [comment]
Hi Guoliang,
Can you clarify your question? I am not sure what you are asking.

**Comment by lyuguol** [comment]
> Hi Guoliang,
> Can you clarify your question? I am not sure what you are asking.

Hi Yuqi, many thanks for the reply!

I want to use 'stList_tm10x_full.rda' for the training. 

When going to the steps that need the 'newAnn' in the stTM (i.e. meta data), I could not find that and tried to use 'cell_ontology_class'. But failed. 

So, I was wondering there is any method to make the 'sampTab' from '10x_full' similar to 'stTM' from the example.
Becasue the stTM is suitable for:
stList <- splitCommon(sampTab = stTM, ncells = 100, dLevel = "newAnn")
system.time(class_info <- scn_train(stTrain = stTrain, expTrain = expTrain, nTopGenes = 10, nTopGenePairs = 25, nRand = 70, nTrees = 1000, dLevel = "newAnn", colName_samp = "cell"))

Below was how I get and check the meta data of 'stList_tm10x_full' and the example data:

### Load 'stList_tm10x_full': 
expTMraw <- utils_loadObject("SingleCellNet/stList_tm10x_full.rda")

### get the 'meta data':
sampTab <- expTMraw$sampTab
str(sampTab)
'data.frame':	70118 obs. of  10 variables:
 $ cell               : chr  "10X_P4_0_AAACCTGAGATTACCC" "10X_P4_0_AAACCTGAGTGCCAGA" "10X_P4_0_AAACCTGCAAATCCGT" "10X_P4_0_AAACCTGGTAATCGTC" ...
 $ channel            : chr  "10X_P4_0" "10X_P4_0" "10X_P4_0" "10X_P4_0" ...
 $ mouse.id           : chr  "3-M-8" "3-M-8" "3-M-8" "3-M-8" ...
 $ tissue             : chr  "Tongue" "Tongue" "Tongue" "Tongue" ...
 $ subtissue          : logi  NA NA NA NA NA NA ...
 $ mouse.sex          : chr  "M" "M" "M" "M" ...
 $ method             : chr  "droplet" "droplet" "droplet" "droplet" ...
 $ cell_ontology_class: chr  "basal cell of epidermis" "keratinocyte" "keratinocyte" "basal cell of epidermis" ...
 $ cell_ontology_id   : chr  "CL:0002187" "CL:0000312" "CL:0000312" "CL:0002187" ...
 $ free_annotation    : chr  "proliferating" "differentiated" "suprabasal differentiating" "basal cells" ...
 - attr(*, "problems")= tibble [8,052 × 5] (S3: tbl_df/tbl/data.frame)
  ..$ row     : int [1:8052] 5590 5591 5592 5593 5594 5595 5596 5597 5598 5599 ...
  ..$ col     : chr [1:8052] "subtissue" "subtissue" "subtissue" "subtissue" ...
  ..$ expected: chr [1:8052] "1/0/T/F/TRUE/FALSE" "1/0/T/F/TRUE/FALSE" "1/0/T/F/TRUE/FALSE" "1/0/T/F/TRUE/FALSE" ...
  ..$ actual  : chr [1:8052] "hepatocytes" "hepatocytes" "hepatocytes" "hepatocytes" ...
  ..$ file    : chr [1:8052] "'TM_droplet_metadata.csv'" "'TM_droplet_metadata.csv'" "'TM_droplet_metadata.csv'" "'TM_droplet_metadata.csv'" ...
 - attr(*, "spec")=
  .. cols(
  ..   cell = col_character(),
  ..   channel = col_character(),
  ..   mouse.id = col_character(),
  ..   tissue = col_character(),
  ..   subtissue = col_logical(),
  ..   mouse.sex = col_character(),
  ..   method = col_character(),
  ..   cell_ontology_class = col_character(),
  ..   cell_ontology_id = col_character(),
  ..   free_annotation = col_character()
  .. )

### Load and checked 'stTM' from the example:
stTM <- utils_loadObject("SingleCellNet/sampTab_TM_053018.rda")
str(stTM)
'data.frame':	24936 obs. of  17 variables:
 $ cell               : Factor w/ 55656 levels "10X_P4_0_AAACCTGAGATTACCC",..: 41877 41883 41911 41932 41964 42046 42063 42064 42097 42165 ...
 $ cell_ontology_class: Factor w/ 58 levels "","alveolar macrophage",..: 2 2 2 2 2 2 2 2 2 2 ...
 $ cell_ontology_id   : Factor w/ 58 levels "","CL:0000057",..: 24 24 24 24 24 24 24 24 24 24 ...
 $ channel            : Factor w/ 28 levels "10X_P4_0","10X_P4_1",..: 26 26 26 26 26 26 26 26 26 26 ...
 $ cluster.ids        : int  5 5 5 5 5 5 5 5 5 5 ...
 $ free_annotation    : Factor w/ 55 levels "","alveolar epithelial type 2 cells",..: 1 1 1 1 1 1 1 1 1 1 ...
 $ mouse.id           : Factor w/ 7 levels "3-F-56","3-F-57",..: 4 4 4 4 4 4 4 4 4 4 ...
 $ mouse.sex          : Factor w/ 2 levels "F","M": 2 2 2 2 2 2 2 2 2 2 ...
 $ subsetA            : Factor w/ 3 levels "","False","True": 1 1 1 1 1 1 1 1 1 1 ...
 $ subsetA_cluster.ids: num  NA NA NA NA NA NA NA NA NA NA ...
 $ subsetB            : Factor w/ 3 levels "","False","True": 1 1 1 1 1 1 1 1 1 1 ...
 $ subsetB_cluster.ids: num  NA NA NA NA NA NA NA NA NA NA ...
 $ subtissue          : Factor w/ 3 levels "","hepatocytes",..: 3 3 3 3 3 3 3 3 3 3 ...
 $ tissue             : Factor w/ 12 levels "Bladder","Heart_and_Aorta",..: 6 6 6 6 6 6 6 6 6 6 ...
 $ tissue_tSNE_1      : num  28.7 29.3 30.5 20.5 29.3 ...
 $ tissue_tSNE_2      : num  22.4 25 22.1 14.2 21.8 ...
 $ newAnn             : Factor w/ 52 levels "alveolar macrophage",..: 1 1 1 1 1 1 1 1 1 1 ...

I hope the description is clear to you.

Thanks a lot!

Best,

Guoliang

**Comment by yuqiyuqitan** [comment]
If I understand you correctly, you just need to specify dLevel to be 'cell_ontology_class'. 
`stList <- splitCommon(sampTab = stTM, ncells = 100, dLevel = "cell_ontology_class")
system.time(class_info <- scn_train(stTrain = stTrain, expTrain = expTrain, nTopGenes = 10, nTopGenePairs = 25, nRand = 70, nTrees = 1000, dLevel = "cell_ontology_class", colName_samp = "cell"))`

**Comment by lyuguol** [comment]
> system.time(class_info <- scn_train(stTrain = stTrain, expTrain = expTrain, nTopGenes = 10, nTopGenePairs = 25, nRand = 70, nTrees = 1000, dLevel = "cell_ontology_class", colName_samp = "cell"))

Dear Yuqi,

Many thanks for the reply. Yes, you understood me correctly!

Actually I have tried the suggested commands. But encountered the error as below. It is the specific error that makes me thinking about cleaning the sampTab in the 'stList_tm10x_full'.

### Input
expTMraw <- utils_loadObject("SingleCellNet/stList_tm10x_full.rda")
expTM <- expTMraw$expDat
stTM <- expTMraw$sampTab

seuratfile <- extractSeurat(scRNA, exp_slot_name = "counts")
expQuery <- seuratfile$expDat
stQuery <- seuratfile$sampTab
genesQuery <- rownames(expQuery)

commonGenes <- intersect(rownames(expTM), genesQuery)
expTrain <- expTM[commonGenes, ]

stList <- splitCommon(sampTab = stTM, ncells = 100, dLevel = "cell_ontology_class")
stTrain <- stList[[1]]
expTrain <- expTrain[, rownames(stTrain)]

### Error:
Error in intI(j, n = x@Dim[2], dn[[2]], give.dn = FALSE) : 
  invalid character indexing

Could you show me how to fix this error?

Many thanks,

Guoliang

**Comment by yuqiyuqitan** [comment]
Hi Guoliang,

So the line of `expTrain <- expTrain[, rownames(stTrain)]` aims to subset your training dataset based on your training sample table, and it assumes that your sample table has row names that match your cell barcodes. In this particular dataset, I just checked, the row names do not match your cell barcode. So I would recommend you do this instead `expTrain <- expTrain[, as.vector(stTrain$cell)]` or before subsetting do this `rownames(sampTab) = as.vectorsampTab$cell)`

**Comment by lyuguol** [comment]
> rownames(sampTab) = as.vectorsampTab$cell)

Hi Yuqi, thank you for the quick reply. I re-run the following commands:

expTMraw <- utils_loadObject("SingleCellNet/stList_tm10x_full.rda")
expTM <- expTMraw$expDat
stTM <- expTMraw$sampTab
rownames(stTM) <- as.vector(stTM$cell)
seuratfile <- extractSeurat(scRNA, exp_slot_name = "counts")
expQuery <- seuratfile$expDat
stQuery <- seuratfile$sampTab
genesQuery <- rownames(expQuery)
commonGenes <- intersect(rownames(expTM), genesQuery)
expTrain <- expTM[commonGenes, ]
set.seed(123)
stList <- splitCommon(sampTab = stTM, ncells = 100, dLevel = "cell_ontology_class")

head(stList$train$cell)
[1] NA                          NA                          NA                         
[4] "10X_P4_0_GTTCGGGCACCCAGTG" NA                          NA  

stTrain <- stList[[1]]
expTrain <- expTrain[, as.vector(stTrain$cell)]

Error in intI(j, n = x@Dim[2], dn[[2]], give.dn = FALSE) : 
  invalid character indexing

I think maybe it is the 'splitCommon' step, which leads to the error.

What do you think?

Best,

Guoliang

**Comment by yuqiyuqitan** [comment]
Hi Guoliang,

The reason why that subsetting didn't work is that the expression matrix is a Sparse matrix. `expTrain <- expDat[, colnames(expDat) %in% as.vector(stTrain$cell)]` I have tested this line of code works. or use `expDat = as.matrxi(expDat)` then `expTrain[, as.vector(stTrain$cell)]` would work.

**Comment by lyuguol** [comment]
> expTrain[, as.vector(stTrain$cell)]

Hello Yuqi,

Thank you for the kind help! The code managed to subset. However, another error shows. I list as below:

expTMraw <- utils_loadObject("SingleCellNet/stList_tm10x_full.rda")
expDat <- expTMraw$expDat
stTM <- expTMraw$sampTab
commonGenes <- intersect(rownames(expDat), genesQuery)
expTrain <- expDat[commonGenes, ]
set.seed(123)
stList <- splitCommon(sampTab = stTM, ncells = 100, dLevel = "cell_ontology_class")
stTrain <- stList[[1]]
expTrain <- expTrain[, colnames(expTrain) %in% as.vector(stTrain$cell)] ## all went well until this step
### Then
system.time(class_info <- scn_train(stTrain = stTrain, expTrain = expTrain, nTopGenes = 10, nTopGenePairs = 25, nRand = 70, nTrees = 1000, dLevel = "cell_ontology_class", colName_samp = "cell"))
### Error 
Error in `.rowNamesDF<-`(x, value = value) : 
  duplicate 'row.names' are not allowed
In addition: Warning message:
non-unique values when setting 'row.names':  
Timing stopped at: 0.002 0 0.001


Do you have any idea about this error?

Many thanks.

Guoliang

**Comment by yuqiyuqitan** [comment]
Hi Guoliang,

Try this `rownames(expTrain) = make.names(sampTab$cell, unique = TRUE)`. Also, I think most of these errors would be solved effectively by Googling the error message.

**Comment by yuqiyuqitan** [comment]
Hi Guoliang,

I have looked deeper into this dataset and why it is causing you so many errors. It turns out there are NAs in the cell_ontology_class, aka there are cells without annotations. If you have looked into your stTrain object after splitCommons, you would have noticed that it returns a lot of NAs. To remedy this **1**) I have uploaded a new stList_tm10x_full_011521.rda dataset under the same downloading hyperlink that removes all the cells without labels (**with that, also I have tested the whole SCN pipeline till scn_predict and it works fine**) **2**) I have added a stop message to splitCommons so that it will alert you if your annotations have NAs in them. 

On a different note, I would recommend you to comb through the cell_ontology_class and subset the cell types that actually might be relevant. This will significantly reduce your training time and the interpretability of your results.

Best
Yuqi

**Comment by lyuguol** [comment]
> Hi Guoliang,
> 
> I have looked deeper into this dataset and why it is causing you so many errors. It turns out there are NAs in the cell_ontology_class, aka there are cells without annotations. If you have looked into your stTrain object after splitCommons, you would have noticed that it returns a lot of NAs. To remedy this **1**) I have uploaded a new stList_tm10x_full_011521.rda dataset under the same downloading hyperlink that removes all the cells without labels (**with that, also I have tested the whole SCN pipeline till scn_predict and it works fine**) **2**) I have added a stop message to splitCommons so that it will alert you if your annotations have NAs in them.
> 
> On a different note, I would recommend you to comb through the cell_ontology_class and subset the cell types that actually might be relevant. This will significantly reduce your training time and the interpretability of your results.
> 
> Best
> Yuqi

Hello Yuqi, 

Thank you so much for the great efforts!!

Yes, it goes well to the end by using the new data!! Amazing!!

I would not subset the cell types subjectively since my sequenced sample has not been reported yet. I would like to know which cell type it is similar to. I tried different 'cell type identification' method, the 'SingleCellNet' developed by you gave me the most informative results.

Many thanks again!!

All the best,

Guoliang
