### ISSUE TITLE
error: package ‘ps’ does not have a namespace

### ISSUE THREAD

**Issue by hyjforesight** [pcahan1/singleCellNet#35]
Hi SingleCellNet,
I cannot install the package. Could you please help me? Thanks!

> install.packages("devtools")
trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.0/devtools_2.3.2.zip'
Content type 'application/zip' length 448584 bytes (438 KB)
downloaded 438 KB

package ‘devtools’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\Yuanjian\AppData\Local\Temp\RtmpWa9dNR\downloaded_packages
> devtools::install_github("pcahan1/singleCellNet")
Error: .onLoad failed in loadNamespace() for 'processx', details:
  call: NULL
  error: package ‘ps’ does not have a namespace

**Comment by yuqiyuqitan** [comment]
Hi Yuanjian,

Unfortunately, I was not able to reproduce your error. Have you tried `install.packages("ps")`? 

Best,
Yuqi

**Comment by hyjforesight** [comment]
Hello Yuqi,
Thanks for help!
After install.packages("ps"), I still cannot install the SingleCellNet. Please see below. Thanks!

install.packages("devtools")
trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.0/devtools_2.3.2.zip'
Content type 'application/zip' length 448198 bytes (437 KB)
downloaded 437 KB

package ‘devtools’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\Yuanjian\AppData\Local\Temp\RtmpM96ukr\downloaded_packages
> devtools::install_github("pcahan1/singleCellNet")
Downloading GitHub repo pcahan1/singleCellNet@HEAD
√  checking for file 'C:\Users\Yuanjian\AppData\Local\Temp\RtmpM96ukr\remotes3034501526db\pcahan1-singleCellNet-7574c9b/DESCRIPTION' ...
-  preparing 'singleCellNet':
√  checking DESCRIPTION meta-information ... 
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  building 'singleCellNet_0.1.0.tar.gz'
   
* installing *source* package 'singleCellNet' ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** byte-compile and prepare package for lazy loading
Error: (converted from warning) package 'dplyr' was built under R version 4.0.4
Execution halted
ERROR: lazy loading failed for package 'singleCellNet'
* removing 'C:/R/library/singleCellNet'
Error: Failed to install 'singleCellNet' from GitHub:
  (converted from warning) installation of package ‘C:/Users/Yuanjian/AppData/Local/Temp/RtmpM96ukr/file303445d84976/singleCellNet_0.1.0.tar.gz’ had non-zero exit status
> library(singleCellNet)
Error in library(singleCellNet) : 
  there is no package called ‘singleCellNet’

**Comment by yuqiyuqitan** [comment]
The error message seems to suggest that your 'dplyr' version is not compatible. Though I don't know why that might be the case since I am currently using an R version 4.0.3 which is very close to yours. My dplyr package version is 1.0.4. Without able to replicate your error, I would suggest installing dplyr with the 1.0.4 version.

**Comment by hyjforesight** [comment]
I updated my R to 4.0.4 and install dplyr. Now I can load the singcellnet. Thanks Yuqi!
