### ISSUE TITLE
how to create rda file for pbmc dataset from 10X?

### ISSUE THREAD

**Issue by hyjforesight** [pcahan1/singleCellNet#36]
Hello Yuqi,
I'm trying to run the SingleCellNet by using the public PBMC dataset from 10X. I downloaded from the Seurat website (https://satijalab.org/seurat/articles/pbmc3k_tutorial.html). It includes matrix.mtx, barcodes.tsv and genes.tsv.
How could I transfer it into the rda file?
Do I need to do QC, normalizing, scaling, PCA and cell clustering before running the SingleCellNet?
Thanks!
Best,
YJ

**Comment by yuqiyuqitan** [comment]
Hi YJ,

So there is a function in SCN called extractSeurat(seurat_object, exp_slot_name = "counts"), where you can extract your Seurat object into a list that contains your sample table and expression matrix then use them for SCN. You need QC for better quality data and clustering annotation for better visualization [basically perform the standard preprocessing that you would in Seurat]. However, I would recommend using the QC-ed raw gene expression matrix with your Seurat cluster for SCN input. 

Best
Yuqi

**Comment by hyjforesight** [comment]
Hello Yuqi,
I've imported the Serut data by your methods. Thanks for help!
Best,
YJ
