### ISSUE TITLE
An error in scn_train: new columns would leave holes after existing columns

### ISSUE THREAD

**Issue by 10myl200** [pcahan1/singleCellNet#39]
Hello!
I'm using given MWS data (mouse atlas microwell-seq) for training.
However, while running the scn_train function, I got an error like below.

> Error in `[<-.data.frame`(`*tmp*`, Matrix::which(tmpAns < dThresh), value = 0) :
>   new columns would leave holes after existing columns
> Calls: system.time -> scn_train -> trans_prop -> [<- -> [<-.data.frame

Could you check this problem?
Thank you!

**Comment by yuqiyuqitan** [comment]
Try make the expression matrix from sparse matrix to a fully connected dense matrix via `as. matrix()`.

**Comment by 10myl200** [comment]
Thanks for your quick reply! It solved the error :)
But I got another one from the assign_cate function.
```
Error in data.frame(..., check.names = FALSE) :
  arguments imply differing number of rows: 16438, 16488
Calls: assign_cate -> cbind -> cbind -> data.frame
```

**Comment by yuqiyuqitan** [comment]
You have created cells for the random category (as controls). You can set scn_predict(nrand=0) or subset out the cell profiles that present in your original data frame.
