### ISSUE TITLE
Singlecellnet introduces "rand" as new cells in the prediction output

### ISSUE THREAD

**Issue by matt-sd-watson** [pcahan1/singleCellNet#43]
Hello, 

I have been reviewing some of the previous issues on the "rand" annotation category specifically in #20 and #28. 

However, I also noticed that upon prediction for my query dataset using the RF model, singlecellnet introduced 50 new columns in the same location where my cells barcodes are held, each being labelled "rand#" i.e. rand1, rand2 etc.. This caused my prediction output data frame to contain more "cells" (6326) than actual cells in my Seurat object (6276), and required removal prior to merging. 

Is this expected behaviour, and if so, could you explain why the package is introducing "new" cells into the prediction? I understand why an individual cell would be annotated as "rand" in certain circumstances, but I do not understand why, in the output prediction frame, new columns are introduced that resemble cells that are named "rand".

**Comment by yuqiyuqitan** [comment]
Hi, the "new" cells serve as a positive control to attest to the functionality of the "rand" category which prevents your query cells from being forcefully classified as the most similar label in your training. So if most if not all these "new" cells are classified as rand, it means your rand category is working properly. If you don't want to introduce any new "rand" cells, set the nrand parameter in scn_predict to 0.

**Comment by matt-sd-watson** [comment]
Thank you for the information!
