### ISSUE TITLE
How to increase font size in sc_violinClass and other SCN plots?

### ISSUE THREAD

**Issue by bijuissacch224610** [pcahan1/singleCellNet#44]
Hello SCN Team

Could you tell me how to increase font size in the SCN output images e.g. sc_violinClass as I need them for submitting to manuscripts. current plots have small fonts as the celltypes increase in training model

Thanks
<img width="232" alt="Screen Shot 2022-06-22 at 12 57 26 PM" src="https://user-images.githubusercontent.com/83024487/175095071-afe49d45-4e40-46e2-b882-109c595d9821.png">

-Biju

**Comment by yuqiyuqitan** [comment]
Hi Biju, you might have to go into the code to adjust the font size. While I am working on this improvement, which might take some time, here is what you can do. 
Here is the source code for sc_violinClass. if you want to change the font size for cell type, just go down to where I indicated as **change size here** and change the number. afterward, source that function or simply run it on your R console. And you should be good to go.

`sc_violinClass<-function
(sampTab,
 classRes,
 sid = "cell_name",
 dLevel="cluster",
 addRand=0,
 threshold=0.20, 
 ncol =1,
 sub_cluster = NA){

  rownames(sampTab) = sampTab[,sid]
  sids <- rownames(sampTab)
  colnames(sampTab)[which(colnames(sampTab) == dLevel)] = "cluster"
  dLevel = "cluster"
  classRes<-classRes[,sids]
  stQ2<-cbind(sampTab[sids,], t(classRes[,sids]))

  maxX <-apply(classRes, 1, max)
  meaVar <-names(which(maxX>threshold))

  test <- melt(stQ2, id.vars = c(sid, dLevel), measure.vars =  meaVar)

  cnames <- colnames(test)
  cnames[which(cnames=='value')] <- "classification_score"
  cnames[which(cnames=='variable')] <- "cell_type"
  colnames(test) <- cnames
  xcol = length(unique(sampTab[,dLevel]))
  getPalette <- colorRampPalette(brewer.pal(xcol, "Set2"))
  if(!is.na(sub_cluster)){
    test = test[test$cluster %in% sub_cluster,]
  }

ggplot(test, aes(x = cluster, y = classification_score, fill = cluster)) + ylim(0,1) + geom_violin(scale='width', position='dodge', trim=FALSE) + 
  facet_wrap(~ cell_type, ncol=ncol) + 
   coord_cartesian(clip = "off") +
   theme_dviz_hgrid() +
   theme(
     axis.line.x = element_blank(),
     axis.ticks.x = element_blank(), 
     axis.title.y = element_text(size = 8), 
    axis.title.x = element_text(size = 8), **#change size here**
    axis.text.x = element_text(size = 8, angle = 45, hjust=1),
    axis.text.y = element_text(size = 8),
    legend.title=element_text(size=10), 
    legend.text=element_text(size=10),
    strip.text.x = element_text(size = 8)
   ) + geom_boxplot(width=0.1, outlier.size=.25) + scale_fill_manual(values = getPalette(xcol))

}`

**Comment by bijuissacch224610** [comment]
Thanks
