### ISSUE TITLE
warnings and error related to scn_train: "In sqrt(as.numeric(llfit$summary[, 2])) : NaNs produced"

### ISSUE THREAD

**Issue by alexwang1001** [pcahan1/singleCellNet#50]
Hi! Could you help me with this? I am using singleCellNet to train a classifier using a single cell dataset with 15729 genes, 9 categories, and 3600 cells (400 cells per category).
```
dim(expTrain)
[1] 15729  3600
```
I wonder why I received this warning when running `scn_train` :
```
class_info <- scn_train(stTrain = stTrain, expTrain = expTrain, nTopGenes = 50, nRand = 400, nTrees = 1000, nTopGenePairs = 125, dLevel = "type", colName_samp = "cell")
Warning messages:
1: In sqrt(as.numeric(llfit$summary[, 2])) : NaNs produced
2: In sqrt(as.numeric(llfit$summary[, 2])) : NaNs produced
3: In sqrt(as.numeric(llfit$summary[, 2])) : NaNs produced
4: In sqrt(as.numeric(llfit$summary[, 2])) : NaNs produced
5: In sqrt(as.numeric(llfit$summary[, 2])) : NaNs produced
6: In sqrt(as.numeric(llfit$summary[, 2])) : NaNs produced
```

Also, when I set nTopGenes = 50, and nTopGenePairs =150, I received this error at the same time when running `scn_train` :
```
Error in if ((countList[tgp[1]] < maxPer) & (countList[tgp[2]] < maxPer)) { : 
  missing value where TRUE/FALSE needed
```

The error seems to be related to nTopGenePairs, as when I set it below 125, there is no error. The warning is always present.
Thank you for your help in advance!

**Comment by yuqiyuqitan** [comment]
Without knowing what your expTrain looks like, I would assume there are missing values or NAs in it. As long as you didn't get an error, I wouldn't worry about the warning messages. As for the second error, I would recommend keeping the number of nTopGenePairs low or further increasing the nTopGenes, maybe there aren't enough distinct combinations of gene pairs to be generated from your 50 topGenes.

**Comment by alexwang1001** [comment]
Thank you for your prompt reply. Indeed, increasing the nTopGenes solved the error. However, I still get the same warnings. There is no missing values or NAs in the expTrain
```
> dim(expTrain)
[1] 15729  3600
> dim(is.na(expTrain))
[1] 15729  3600
> sum(is.na(expTrain))
[1] 0
```
Removing genes with 0 variance also does not help. This is somewhat weird. The results, however, seem okay.
