### ISSUE TITLE
Transcription factor

### ISSUE THREAD

**Issue by bali-eng** [pcahan1/singleCellNet#55]
Hi,

Thank you for your excellent work. In Figure 2 (E), you mentioned that in this classification heatmap, the columns annotate the five different transcription factor pairs used to generate each iN profile. My question is, how did you define these five transcription factor pairs? Could you please elaborate on that?

Thanks

**Comment by pcahan1** [comment]
The columns that are referred to in the caption of Fig 2E of [PMID: 31377170](https://pubmed.ncbi.nlm.nih.gov/31377170/) are the broad groups of columns indicated by the color band at the top of the heatmap. Each group of columns or cells, was converted to an iN with a different set of TFs, as indicated by the legend, for example the first group of cells was induced with Ascl2 and Nr4a2. These pairs of TFs were identified and experimentally tested as described in [PMID: 29743677](https://pubmed.ncbi.nlm.nih.gov/29743677/). Thank you.

**Comment by bali-eng** [comment]
Thanks for your clarification.
